# Generated by Django 3.1.1 on 2020-09-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoryapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='points',
            new_name='score',
        ),
    ]
